name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    setps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
